### PR TITLE
Fix invalid char for report name

### PR DESCRIPTION
**Pull request by jayrbolton**

### CODE REVIEW

**Comment by jayrbolton** [comment]
Tests pass

**Review by psdehal — CHANGES_REQUESTED** [review]
Looks good, but I think it's good practice to make an entry in the change log, even if it's a minor bug fix.

**Comment by jayrbolton** [comment]
Okay will do

**Comment by jayrbolton** [comment]
Done.
I'll leave it to the next dev support person to get this merged and released.

**Comment by psdehal** [comment]
Thanks

**Pull request merged**
